### ISSUE TITLE
Trying to register a metric with an existing name causes program termination

### ISSUE THREAD

**Issue by cfsmp3** [digitalocean/prometheus-client-c#29]
```
prom_collector_registry_must_register_metric()
```
just terminates the program if a metric with the same name already exists.

**Comment by miroswan** [comment]
[This is by design and documented](https://digitalocean.github.io/prometheus-client-c/prom__collector__registry_8h.html#a113683f4e15ad9240a37ed2139ddaea6)

If you do not want the program to exit in this scenario, then try using [prom_collector_registry_register_metric](https://digitalocean.github.io/prometheus-client-c/prom__collector__registry_8h.html#aa735fa0fbe03d6d9a0d11eb4792ec761)
