### ISSUE TITLE
Support build in local machine (not in docker container)

### ISSUE THREAD

**Issue by prksu** [digitalocean/prometheus-client-c#9]
i want to build this project on my mac (not in a container). 

when i run `./auto build` i got an error `CPack package description file: "/code/README.md" could not be found.`

this is full output

```bash
$ ./auto build

########################################################################
> Executing build
########################################################################


########################################################################
> prom: CMake Build Stage
########################################################################

-- The C compiler identification is GNU 9.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-9
-- Check for working C compiler: /usr/local/bin/gcc-9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CPack.cmake:523 (message):
  CPack package description file: "/code/README.md" could not be found.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CPack.cmake:527 (cpack_check_file_exists)
  CMakeLists.txt:136 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/prksu/Developer/c/prometheus-client-c/prom/build/CMakeFiles/CMakeOutput.log".
ERROR: prom: CMake Failure
```

this error can be solved with change `/code/README.md` to `${CMAKE_CURRENT_SOURCE_DIR}/../README.md)` and i can build this project both in local machine and in container.

i have see README that one of the dependencies needed is a docker. my question, is there a plan to support build this project on the local machine? maybe it would be great.

**Comment by miroswan** [comment]
As a first step, you can enter the development environment by executing `auto dev`. Docker will be need to be up and running since it drops you into the development container. A subsequent `auto build` will build the project and `auto build -t` will build the project with tests. There is help output for the tool if you want more information about each subcommand and their associated options. 

We currently support development of the library within the container to keep things consistent. However, if you have an update that will fix this issue for your development environment and not break the dev container then I'll be happy to review a PR.

**Comment by prksu** [comment]
sound good, i will send PR in few day
